version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - abruere
  labels:
  - "type: Dependencies"
  ignore:
  - dependency-name: vue-intl
    versions:
    - 4.1.15
    - 4.1.17
    - 4.1.18
    - 4.1.22
    - 4.1.26
    - 4.1.27
  - dependency-name: quasar
    versions:
    - 1.15.1
    - 1.15.2
    - 1.15.3
    - 1.15.4
    - 1.15.5
    - 1.15.7
    - 1.15.9
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: copy-webpack-plugin
    versions:
    - 7.0.0
    - 8.0.0
    - 8.1.0
  - dependency-name: socket.io-client
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: "@quasar/app"
    versions:
    - 2.1.14
    - 2.1.15
    - 2.2.1
    - 2.2.3
  - dependency-name: mapbox-gl
    versions:
    - 2.0.1
    - 2.1.0
  - dependency-name: commander
    versions:
    - 7.0.0
